"""
Django settings for PoetsDuel project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

LOGIN_URL= '/users/signin/'
LOGOUT_URL='/users/signin/'
LOGIN_REDIRECT_URL='/index/mvc/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL='index2'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9gg#qrrgekgydctb@w($f=s9ycqt9!9e_%k^i82r6a2m@2+5_v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1','45.55.247.92','www.blumury.com','192.168.0.102', 'justaskvaish.pythonanywhere.com', 'blumury.com']


# Application definition

INSTALLED_APPS = [
    'auth_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'writers_block',
    'django.contrib.humanize',
    'portfolio',
    'social_django',
    'tinymce',
    'notifications',
    'django_social_share',
    'chat'

]

SOCIAL_AUTH_TWITTER_SCOPE = ['email']
SOCIAL_AUTH_TWITTER_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email', 
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PoetsDuel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'auth_app.context_processors.base_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'PoetsDuel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'reels',
        'USER': 'vaish',
        'PASSWORD': 'doingmanthram@hogwarts',
        'HOST':'localhost',
        'PORT':''
    }
}


AUTHENTICATION_BACKENDS ={
    'django.contrib.auth.backends.ModelBackend',
    'auth_app.authentication.EmailAuthenticationBackend',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2'
}

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'auth_app.authentication.get_avatar'
)

SOCIAL_AUTH_TWITTER_KEY='SLznMmT66PFOpAuExlZMnWAWi'
SOCIAL_AUTH_TWITTER_SECRET='32xcqkKfEu3ddJgMwOtryPKJP3NBjNG1q4tUiFFyXhHy3apajd'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='1071736090684-bg06v95e00dml6nr5ej8l95velhkpauk.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='K9vKH-CyLsL9wm-ZVWx52fNE'

SOCIAL_AUTH_FACEBOOK_KEY = '332820377169948'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '9663ce5a2a898ed99709a22071b73a31' # App Secret


SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email', 
}


ALLOWED_UPLOAD_IMAGES=['jpeg', 'jpg', 'png', 'gif']

# Password validationgo

# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR,'static')

STATICFILES_DIRS=(os.path.join(BASE_DIR, 'staticfiles'), )

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

STATIC_DOC_ROOT = os.path.join(os.getcwd(), 'site_media')
STATIC_DOC_URL = '/site_media/'


