# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170819_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='chats',
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
    ]
