# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/std_avatar.jpeg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='/std_thumb.jpeg', upload_to='thumbnails/'),
        ),
    ]
