# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writers_block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(related_name='bups', to=settings.AUTH_USER_MODEL),
        ),
    ]
