# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_block', '0002_comment_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.CharField(max_length=4000),
        ),
    ]
