# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170804_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
