# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_piece_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
