# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170809_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='summary',
            field=models.CharField(default='lol', max_length=300),
        ),
    ]
