# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 06:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0005_piece_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcomment',
            name='upvotes',
            field=models.ManyToManyField(related_name='pups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='piece',
            name='summary',
            field=models.CharField(default='lo', max_length=300),
        ),
    ]
